/**
 * The vendored engine and data are Agent_Loop_Sim's files at the pinned commit, byte for byte;
 * the data files match the engine's manifest; and the site's fixtures were generated by the
 * Python reference at that same commit.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import VENDORED from "@/lib/engine/vendor/VENDORED.json";

const ROOT = join(__dirname, "../..");
const sha = (b: Buffer) => createHash("sha256").update(b).digest("hex");

describe("vendored engine", () => {
  it("every file matches the SHA-256 recorded with its commit", () => {
    const files = Object.entries(VENDORED.files);
    expect(files.length).toBeGreaterThanOrEqual(40);
    expect(VENDORED.commit).toMatch(/^[0-9a-f]{40}$/);
    for (const [path, rec] of files)
      expect(sha(readFileSync(join(ROOT, path))), path).toBe(rec.sha256);
  });

  it("vendors the TS port with its context module, the tokenizer and the context data", () => {
    const froms = Object.values(VENDORED.files).map((f) => f.from);
    for (const f of [
      "ts/src/context/corpus.ts",
      "ts/src/context/chunking.ts",
      "ts/src/context/retrieval.ts",
      "ts/src/context/evaluate.ts",
      "ts/src/context/window.ts",
      "ts/src/context/views.ts",
      "ts/src/context/mathx.ts",
      "ts/src/tokenizer.ts",
      "src/agent_loop_sim/data/qwen2.5-merges.txt",
      "src/agent_loop_sim/data/context/corpus.json",
      "src/agent_loop_sim/data/context/manifest.json",
      "src/agent_loop_sim/data/context/rerank.json",
      "fixtures/context_fixtures.json",
      "fixtures/context_results.md",
    ])
      expect(froms).toContain(f);
  });

  it("each data file is the one the engine's manifest names (model run offline, once)", () => {
    const man = JSON.parse(
      readFileSync(join(ROOT, "public/context/manifest.json"), "utf8"),
    ) as {
      files: Record<string, string>;
      corpus: { licence: string };
      embedder: { revision: string; licence: string };
      reranker: { revision: string; licence: string };
    };
    expect(Object.keys(man.files).length).toBe(11);
    for (const [n, h] of Object.entries(man.files))
      expect(sha(readFileSync(join(ROOT, "public/context", n))), n).toBe(h);
    expect(man.corpus.licence).toBe("CC BY-SA 4.0");
    expect(man.embedder.licence).toBe("Apache-2.0");
    expect(man.reranker.licence).toBe("Apache-2.0");
  });

  it("the engine's own context fixtures are reproduced by the vendored port", async () => {
    const { ctx } = await import("@/lib/engine");
    const { nodeCorpus } = await import("@/lib/engine/node");
    const fx = JSON.parse(
      readFileSync(join(ROOT, "tests/fixtures/context_fixtures.json"), "utf8"),
    ) as {
      engine: string;
      evals: {
        config: string;
        method: string;
        params: Record<string, unknown>;
      }[];
      chunks: Record<string, number[][]>;
    };
    expect(fx.engine).toBe("1.5.0");
    const c = nodeCorpus();
    for (const [name, want] of Object.entries(fx.chunks))
      expect(
        c.chunks(name).map((x) => [x.article, x.start, x.end, x.tokens]),
      ).toEqual(want);
    // the default chunking's evaluations (all of them are checked in Agent_Loop_Sim's own CI)
    const r = new ctx.Retriever(c, ctx.DEFAULT);
    const mine = fx.evals.filter((e) => e.config === ctx.DEFAULT);
    expect(mine.length).toBeGreaterThanOrEqual(10);
    for (const e of mine)
      expect(ctx.evaluate(r, e.method, e.params)).toEqual(e);
  });

  it("the engine's 1.5 fixtures (packing, compaction, memory, long context) are reproduced by the vendored port", async () => {
    const { ctx } = await import("@/lib/engine");
    const { nodeCorpus } = await import("@/lib/engine/node");
    const fx = JSON.parse(
      readFileSync(join(ROOT, "tests/fixtures/context2_fixtures.json"), "utf8"),
    ) as Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any
    expect(fx.engine).toBe("1.5.0");
    const r = new ctx.Retriever(nodeCorpus(), ctx.DEFAULT);
    for (const w of fx.lossy)
      expect(ctx.windowRun(r, fx.task, w.budget, w.policy, "lossy")).toEqual(w);
    for (const v of fx.packing_views)
      expect(ctx.packingView(r, v.q, v.budget)).toEqual(v);
    const plan = ctx.memoryPlan(r);
    expect(plan).toEqual(fx.memory_plan);
    for (const m of fx.memory.slice(0, 8))
      expect(ctx.memoryRun(r, m.policy, plan, m.name)).toEqual(m);
    const t = fx.tradeoff;
    expect(
      ctx.tradeoff(r, [t.sizes.corpus, 200000, 1000000], [3, 5, 10, 20], 50),
    ).toEqual(t);
  });

  it("the site's fixtures come from the same commit", () => {
    const fx = JSON.parse(
      readFileSync(join(ROOT, "tests/fixtures/site_fixtures.json"), "utf8"),
    ) as { commit: string };
    expect(fx.commit).toBe(VENDORED.commit);
  });
});
